### ISSUE TITLE
Data not saving

### ISSUE THREAD

**Issue by ryanderson** [deepilla/perch-fieldtype-tabular#1]
This fieldtype is something Perch really needs. Are you still supporting/developing? When I click "save" all of the data disappears in the admin area but is output to the website...but has to be re-entered every time (so it is unusable right now). I'm using Perch 2.3.2, PHP 5.4.7, MySQL 5.5.27.

**Comment by deepilla** [comment]
This started happening in Perch 2.3. There was a change in the Perch API that broke the fieldtype. I [reported the issue](http://support.grabaperch.com/index.php?pg=forums.posts&id=7234) two months ago but the Perch team have yet to look into it - low priority apparently.

As for further development/support, I'm still using the tabular fieldtype but I'll probably remove it from Github. My advice would be to use repeaters instead. The UI isn't great right now but I believe that a grid-style display is in the pipeline.

**Comment by ryanderson** [comment]
Ah. Bummer. Thanks for the quick reply. I did know about the potential of the repeater grid style coming but do like how you've done the tabular/table UI and fieldtype settings.
